/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103C6.h"
#include "Stm32_F103C6_GPIO_Driver.h"

void clock_init()
{
	//Enable IO port A clock
	RCC_GPIOA_CLK_EN();
	//Enable IO port B clock
	RCC_GPIOB_CLK_EN();
}

void GPIO_init()
{
	GPIO_PinConfig_t PinCfg;

	// PA1 input HighZ Floating input (reset state)
	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	// PB1 (output push-pull mode)
	// 01: Output mode, max speed 10MHz.
	// CNF 00: General purpose output push-pull
	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	// PA13 input HighZ Floating input (reset state)
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	// PB13 (output push-pull mode)
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);
}
void Wait(int t)
{
	int x,y;
	for(x=0;x<t;x++)
		for(y=0;y<255;y++);
}
int main(void)
{
	clock_init();
	GPIO_init();
	while(1)
	{
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) ==0)
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			// Single Press
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) ==0) ;
		}
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) ==1)
		{
			// Multi Press
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
		}
		Wait(1);
	}
}


