/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//#define MCU_Act_As_Master
#define MCU_Act_As_Slave


#include "Stm32_F103C6.h"
#include "Stm32_F103C6_GPIO_Driver.h"
#include "Stm32_F103C6_EXTI_Driver.h"
#include "Stm32_F103C6_USART_Driver.h"
#include "Stm32_F103C6_SPI_Driver.h"
#include "lcd.h"


unsigned char ch;

void clock_init()
{
	//Enable clock for GPIO
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	//Enable AFIO
	AFIO_CLK_EN();
}

void UART_IRQ_CallBack(void)
{

#ifdef MCU_Act_As_Master

	MCAL_UART_ReceiveData(USART1, &ch, disable);
	MCAL_UART_SendData(USART1, &ch, enable);
	//send to SPI
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 0);
	MCAL_SPI_TX_RX(SPI1, &ch, enable);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 1);

#endif
}

void SPI1_IRQ_CallBack(struct S_IRQ_SRC irq_src)
{
#ifdef MCU_Act_As_Slave
	if(irq_src.RXNE)
	{
		ch=0xf;
		MCAL_SPI_TX_RX(SPI1, &ch, Disable);
		MCAL_UART_SendData(USART1, &ch, enable);

	}
#endif
}
int main(void)
{
	UART_Config uartCfg;
	clock_init();

	//========================UART Init=================================
	//PA9 TX - PA10 RX - PA11 CTS - PA12 RTS
	uartCfg.BaudRate = UART_BaudRate_115200;
	uartCfg.HwFlowCtl = UART_HwFlowCtl_NONE;
	uartCfg.IRQ_Enable = UART_IRQ_Enable_RXNEIE;
	uartCfg.P_IRQ_CallBack = UART_IRQ_CallBack;
	uartCfg.Parity = UART_Parity_NONE;
	uartCfg.Payload_Length = UART_Payload_Length_8B;
	uartCfg.StopBits = UART_StopBits_1;
	uartCfg.USART_Mode = UART_Mode_TX_RX;
	MCAL_UART_Init(USART1, &uartCfg);
	MCAL_UART_GPIO_Set_Pins(USART1);

	//========================SPI Init=================================
	//PA4 NSS - PA5 SCK - PA6 MISO - PA7 MOSI
	SPI_Config SPI1CFG;

	//common Configuration
	SPI1CFG.CLKPhase = SPI_Clock_Phase_2EDGE_Sampling;
	SPI1CFG.CLKPolarity = SPI_CLKPolarity_Idle_HIGH;
	SPI1CFG.DataSize = SPI_DataSize_8BIT;
	SPI1CFG.Frame_Format = SPI_Frame_Format_MSB_First;
	//assume by default pclk2 = 8MHZ
	SPI1CFG.BaudratePrescaler = SPI_BaudratePrescaler_8;
	SPI1CFG.Communication_Mode = SPI_DIRECTION_2LINES;

#ifdef MCU_Act_As_Master
	SPI1CFG.Device_Mode = SPI_Device_Mode_MASTER;
	SPI1CFG.IRQ_Enable = SPI_IRQ_Enable_NONE;
	SPI1CFG.NSS = SPI_NSS_Soft_NSSInternalSoft_Set;
	SPI1CFG.P_IRQ_CallBack = NULL;

	//configure SS on PA4 GPIO
	PinCfg.GPIO_PinNumber = GPIO_PIN_4;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	//force the slave select High idle mode
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 1);

#endif


#ifdef MCU_Act_As_Slave
	SPI1CFG.Device_Mode = SPI_Device_Mode_SLAVE;
	SPI1CFG.IRQ_Enable = SPI_IRQ_Enable_RXNEIE;
	SPI1CFG.NSS = SPI_NSS_Hard_Slave;
	SPI1CFG.P_IRQ_CallBack = SPI1_IRQ_CallBack;

#endif

	MCAL_SPI_Init(SPI1, &SPI1CFG);
	MCAL_SPI_GPIO_Set_Pins(SPI1);


	while(1)
	{

	}
}


