/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103C6.h"
#include "Stm32_F103C6_GPIO_Driver.h"
#include "Stm32_F103C6_EXTI_Driver.h"
#include "lcd.h"
#include "keypad.h"

unsigned int IRQ_Flag = 0;

void Wait(int t)
{
	int x,y;
	for(x=0;x<t;x++)
		for(y=0;y<255;y++);
}

void EXTI9_Callback(void)
{
	IRQ_Flag =1;
	LCD_WRITE_STRING("IRQ EXTI9 is happened _|-  ");
	Wait(1000);
}
int main(void)
{

	//Enable clock
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	AFIO_CLK_EN();

	LCD_INIT();
	LCD_clear_screen();

	EXTI_PinConfig_t EXTI_CGF;
	EXTI_CGF.EXTI_PIN = EXTI9PB9;
	EXTI_CGF.Trigger_Case = EXTI_Trigger_RISING;
	EXTI_CGF.P_IRQ_CallBack = EXTI9_Callback;
	EXTI_CGF.IRQ_EN = EXTI_IRQ_Enable;
	MCAL_EXTI_GPIO_Init(&EXTI_CGF);

	IRQ_Flag = 1;
	while(1)
	{
		if(IRQ_Flag)
		{
			LCD_clear_screen();
			IRQ_Flag =0;
		}
	}
}


